### ISSUE TITLE
Fatal Exception FileNotFoundException

### ISSUE THREAD

**Issue by TriStaRvOiD** [NeoApplications/Neo-Store#186]
Sometimes the app crashes when I'm trying to install any app after it's downloaded

• Samsung, OneUI 4, Android 12
• Droid-ify version 0.43
• arm64

Log:

FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 32682
java.io.FileNotFoundException: /data/user/0/com.looker.droidify/cache/releases/1cee8e4973d8c84927da0adfa0495107b0a81e147c096b16f0ae2e13c4ca4366.apk: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:575)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.looker.droidify.installer.DefaultInstaller.mDefaultInstaller(DefaultInstaller.kt:52)
	at com.looker.droidify.installer.DefaultInstaller.install(DefaultInstaller.kt:36)
	at com.looker.droidify.screen.ScreenActivity$handleSpecialIntent$1.invokeSuspend(ScreenActivity.kt:224)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:256)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
	at com.looker.droidify.screen.ScreenActivity.handleSpecialIntent(ScreenActivity.kt:221)
	at com.looker.droidify.MainActivity.handleIntent(MainActivity.kt:19)
	at com.looker.droidify.screen.ScreenActivity.onNewIntent(ScreenActivity.kt:181)
	at android.app.Activity.performNewIntent(Activity.java:8298)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1429)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1442)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:4243)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:4250)
	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:56)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8641)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8501)
	at libcore.io.IoBridge.open(IoBridge.java:561)
	... 34 more

**Comment by TriStaRvOiD** [comment]
Apparently even though Droid-ify crashed, the app I was trying to update did get updated..even though the file was missing?
