### ISSUE TITLE
Crash on scrolling down app sheet of particular app

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Store#293]
Hi. I opened the app sheet of "Let Me Downgrade" and scrolled down. This caused a crash. The app strangely doesn't have any releases currently, which might be related, and which could mean this needs to be checked before the next F-Droid index update. Note: I opened the same app sheet several times after the crash, but there were no more crashes.

Crash report:
```
FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 25749
java.lang.IllegalStateException: LayoutNode should be attached to an owner
	at androidx.compose.ui.node.LayoutNodeKt.requireOwner(LayoutNode.kt:2)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:14)
	at androidx.compose.foundation.lazy.LazyListPositionedItem.place(LazyMeasuredItem.kt:50)
	at androidx.compose.foundation.lazy.LazyListMeasureKt$measureLazyList$3.invoke(LazyListMeasure.kt:7)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:9)
	at androidx.compose.foundation.lazy.LazyListMeasureResult.placeChildren(Unknown Source:2)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:3)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:16)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:11)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:24)
	at androidx.compose.ui.node.LayoutNode.layoutChildren$ui_release(LayoutNode.kt:16)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:28)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:7)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:5)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:9)
	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:11)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:15)
	at androidx.compose.foundation.layout.FillModifier$measure$1.invoke(Size.kt:3)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:9)
	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:11)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM(Placeable.kt:3)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:4)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:11)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:24)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:17)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM(Placeable.kt:3)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer-aW-9-wM$default(Placeable.kt:2)
	at androidx.compose.foundation.lazy.LazyListPositionedItem.place(LazyMeasuredItem.kt:35)
	at androidx.compose.foundation.lazy.LazyListMeasureKt$measureLazyList$3.invoke(LazyListMeasure.kt:7)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:9)
	at androidx.compose.foundation.lazy.LazyListMeasureResult.placeChildren(Unknown Source:2)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1$measure$1.placeChildren(SubcomposeLayout.kt:3)
	at androidx.compose.ui.node.LayoutNode$layoutChildren$1.invoke(LayoutNode.kt:16)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:11)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:24)
	at androidx.compose.ui.node.LayoutNode.layoutChildren$ui_release(LayoutNode.kt:16)
	at androidx.compose.ui.node.InnerPlaceable.placeAt-f8xVGno(InnerPlaceable.kt:28)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:7)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:5)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:9)
	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:11)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place(Placeable.kt:4)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place$default(Unknown Source:1)
	at androidx.compose.foundation.layout.PaddingValuesModifier$measure$2.invoke(Padding.kt:10)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:9)
	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:11)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:3)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:3)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:11)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:24)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:17)
	at androidx.compose.ui.node.LayoutNode.replace$ui_release(LayoutNode.kt:6)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout-0kLqBqw(MeasureAndLayoutDelegate.kt:13)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout-0kLqBqw(AndroidComposeView.android.kt:2)
	at androidx.compose.ui.node.LayoutNode.forceRemeasure(LayoutNode.kt:8)
	at androidx.compose.foundation.lazy.LazyListState$scrollableState$1.invoke(LazyListState.kt:8)
	at androidx.compose.foundation.gestures.DefaultScrollableState$scrollScope$1.scrollBy(ScrollableState.kt:3)
	at androidx.compose.foundation.gestures.ScrollingLogic.dispatchScroll-f0eR0lY(Scrollable.kt:10)
	at androidx.compose.foundation.gestures.ScrollDraggableState.dragBy-Uv8p0NA(Scrollable.kt:5)
	at androidx.compose.foundation.gestures.DraggableKt$draggable$9$2$2.invokeSuspend(Draggable.kt:8)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:2)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:4)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:965)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:722)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@9cac2ac, androidx.compose.runtime.BroadcastFrameClock@fad7b75, StandaloneCoroutine{Cancelling}@9f9670a, AndroidUiDispatcher@8521b7b]
```

**Comment by machiav3lli** [comment]
Should be fixed on 1.0.0
