### ISSUE TITLE
Try opening menu using navigation bar button -> crash

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Store#300]
If you have the ability to set custom actions for your navigation buttons, like on LOS (or if your OS has this in-built), one option is to open the menu of whatever app is present on screen.

Doing that for this app caused a crash:

```
FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 15732
android.view.InflateException: Couldn't resolve menu item onClick handler syncManual in class com.machiav3lli.fdroid.ui.activities.MainActivityX
	at androidx.appcompat.view.SupportMenuInflater$InflatedOnMenuItemClickListener.<init>(SupportMenuInflater.java:7)
	at androidx.appcompat.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:19)
	at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:25)
	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:5)
	at com.machiav3lli.fdroid.ui.activities.MainActivityX.onCreateOptionsMenu(MainActivityX.kt:1)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4092)
	at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:1)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(Unknown Source:2)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2)
	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:40)
	at androidx.appcompat.app.AppCompatDelegateImpl.dispatchKeyEvent(AppCompatDelegateImpl.java:15)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:4)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5583)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5451)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5150)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:5311)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3065)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2608)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2599)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3042)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:143)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.NoSuchMethodException: com.machiav3lli.fdroid.ui.activities.MainActivityX.syncManual [interface android.view.MenuItem]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at androidx.appcompat.view.SupportMenuInflater$InflatedOnMenuItemClickListener.<init>(SupportMenuInflater.java:4)
	... 41 more
```

**Comment by machiav3lli** [comment]
As far as I know, Compose still has no handle for connecting supportMenu with an action, so this is an external issue on Compose's side

**Comment by opusforlife2** [comment]
Well, I just tried it with the latest version (0.9.5). Something must have changed, because the crash no longer occurs. Instead, the action is ignored now. So... solved?
