### ISSUE TITLE
random crashes in th background

### ISSUE THREAD

**Issue by Quantenzitrone** [NeoApplications/Neo-Store#406]
**Describe the bug**
While I was sleeping my phone did some background updates and stuff and Scoop reported me hourly crashing of Neo Store with this trace:
```
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.machiav3lli.fdroid, PID: 12033
java.lang.IllegalStateException: Mutex is not locked
	at kotlinx.coroutines.sync.MutexImpl.unlock(Mutex.kt:38)
	at com.machiav3lli.fdroid.service.SyncService$onDestroy$1.invokeSuspend(SyncService.kt:55)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
```

**Smartphone (please complete the following information):**

- Device: Shift6m
- OS: Android 8.1
- Version 0.9.13

**Additional context**
I got security vulnerabilities reported for 2 apps in the same night the crashing was happening: `PDF Viewer Plus` & `Firefox Klar` (which is disabled). IDK if that is related.

**Comment by machiav3lli** [comment]
Duplicate of #401
