### ISSUE TITLE
Background crash with the help of scoop detected

### ISSUE THREAD

**Issue by Wladefant** [NeoApplications/Neo-Store#421]
Logs: 

```
FATAL EXCEPTION: DefaultDispatcher-worker-6
Process: com.machiav3lli.fdroid, PID: 24834
java.lang.IllegalStateException: Mutex is not locked
	at kotlinx.coroutines.sync.MutexImpl.unlock(Mutex.kt:38)
	at com.machiav3lli.fdroid.service.SyncService$onDestroy$1.invokeSuspend(SyncService.kt:55)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1fde550, Dispatchers.Default]
```

**Comment by machiav3lli** [comment]
Known and fixed on 0.9.14-alpha01 (available in the community groups)
