### ISSUE TITLE
Crash when sharing market:// URL

### ISSUE THREAD

**Issue by Mrnofish** [NeoApplications/Neo-Store#468]
Report from Intent Intercept:

```
intent://details?id=com.chakaponden.sleepasandroid.go2sleep#Intent;scheme=market;launchFlags=0x13000000;end ACTION: android.intent.action.VIEW
DATA: market://details?id=com.chakaponden.sleepasandroid.go2sleep
URI: intent://details?id=com.chakaponden.sleepasandroid.go2sleep#Intent;scheme=market;launchFlags=0x13000000;end
FLAGS:
FLAG_RECEIVER_FOREGROUND
FLAG_ACTIVITY_FORWARD_RESULT
FLAG_ACTIVITY_PREVIOUS_IS_TOP MATCHING ACTIVITIES:
Aurora Store (com.aurora.store - com.aurora.store.view.ui.details.AppDetailsActivity)
Neo Store (com.machiav3lli.fdroid - com.machiav3lli.fdroid.ui.activities.MainActivityX)
F-Droid Build Status (de.storchp.fdroidbuildstatus - de.storchp.fdroidbuildstatus.MainActivity)
F-Droid (org.fdroid.fdroid - org.fdroid.fdroid.views.main.MainActivity)
```

Stack trace:
```
FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 27987
java.util.NoSuchElementException: List is empty.
at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:8)
at com.machiav3lli.fdroid.ui.viewmodels.AppSheetVM$developer$1.invokeSuspend(AppSheetVM.kt:8)
at com.machiav3lli.fdroid.ui.viewmodels.AppSheetVM$developer$1.invoke(AppSheetVM.kt:13)
at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:44)
at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt:18)
at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:35)
at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:26)
at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:35)
at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:102)
at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:143)
at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:48)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:105)
at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:3)
at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.kt:3)
at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:93)
at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:1)
at kotlinx.coroutines.channels.ChannelCoroutine.send(ChannelCoroutine.kt:3)
at kotlinx.coroutines.flow.internal.SendingCollector.emit(SendingCollector.kt:3)
at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:56)
at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt:18)
at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:35)
at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:26)
at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:35)
at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:102)
at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:5)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:23)
at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:143)
at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7884)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ece7f5f, Dispatchers.Main.immediate]
```

**Comment by machiav3lli** [comment]
Should be fixed on 1.0.0
