### ISSUE TITLE
Rapid double/triple taps on list items can cause crash

### ISSUE THREAD

**Issue by opusforlife2** [NeoApplications/Neo-Store#477]
If you try to rapidly tap on multiple list items repeatedly with several fingers, it can cause a crash. The log remains the same for every such crash, except the value of `Index` in the first line.

Log:

```
FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 6666
java.lang.IndexOutOfBoundsException: Index: 55, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at androidx.compose.runtime.Recomposer.access$recordComposerModificationsLocked(Recomposer.kt:34)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:100)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:775)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@fa895dc, androidx.compose.ui.platform.MotionDurationScaleImpl@c9906e5, StandaloneCoroutine{Cancelling}@75fe5ba, AndroidUiDispatcher@3afac6b]
```

**Comment by machiav3lli** [comment]
This should be fixed in 1.0.0
