### ISSUE TITLE
Crash on repositories selection

### ISSUE THREAD

**Issue by shuvashish76** [NeoApplications/Neo-Store#495]
App crashed while enable-disable same repos multiple times quickly.

**Crash logs :**
```
FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 26958
java.lang.IllegalStateException: Couldn't read row 106, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:511)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
	at com.machiav3lli.fdroid.database.dao.ProductDao_Impl.__entityCursorConverter_comMachiav3lliFdroidDatabaseEntityProduct(ProductDao_Impl.java:181)
	at com.machiav3lli.fdroid.database.dao.ProductDao_Impl$11.call(ProductDao_Impl.java:26)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.kt:84)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

**Device details:**
 - Model - Lenovo Tab4 8 Plus
 - Android - 8.1.0
 - App version - v0.9.15 (927)

**Comment by machiav3lli** [comment]
should be fixed on 1.0.0
