### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Wojtaz0w** [NeoApplications/Neo-Store#500]
I double tapped the back button while in app view -  
and it crashed. https://paste.crdroid.net/flEy9G
```
msg: java.lang.IndexOutOfBoundsException: Index: 18, Size: 0
stacktrace: java.lang.IndexOutOfBoundsException: Index: 18, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at androidx.compose.runtime.Recomposer.access$recordComposerModificationsLocked(Recomposer.kt:34)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:170)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@f4ff07a, androidx.compose.ui.platform.MotionDurationScaleImpl@8aac02b, StandaloneCoroutine{Cancelling}@3831c88, AndroidUiDispatcher@ab4c621]

```

**Comment by machiav3lli** [comment]
This should be fixed in 1.0.0
