### ISSUE TITLE
[Bug] FATAL EXCEPTION

### ISSUE THREAD

**Issue by iplly** [NeoApplications/Neo-Store#661]
**Describe the error**
The application crashed with an error 

**For playback**

1. Scrolling through the application failed

** Relevant information:**

- Device: Oneplus 9r
- Android Version: 14
- ROM: crDroid 10.4
- Application version: 1.0.5

- Which installer did you choose? root

-----------------------------

** Additional notes**
`FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 19143
java.lang.OutOfMemoryError: Failed to allocate a 72 byte allocation with 34424 free bytes and 33KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.database.CursorWindow.nativeGetString(Native Method)
	at android.database.CursorWindow.getString(CursorWindow.java:465)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:54)
	at com.machiav3lli.fdroid.database.dao.ProductDao_Impl$getFlow$1.call(SourceFile:91)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(SourceFile:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@e0376d7, androidx.compose.runtime.BroadcastFrameClock@6f94bc4, StandaloneCoroutine{Cancelling}@ad32aad, AndroidUiDispatcher@1b811e2]`

* If you are using the latest test version (on the TG channel or in the Matrix Room), please report it directly there, not here.

* If you are using the latest version of github:

  * Please review the issues if they match yours, leave a comment if you can provide additional information.

* If you are not using the latest version of github (it takes several days to update the official F-Droid builds). Update, then make sure the error is still there. If so, keep reporting it.

Thanks for the message!

**Comment by j-romchain** [comment]
I'm having this crash as well.

**Comment by j-romchain** [comment]
Heres my crash logcat```
FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 31265
java.lang.OutOfMemoryError: Failed to allocate a 1232 byte allocation with 98744 free bytes and 96KB until OOM, target footprint 268435456, growth limit 268435456; failed due to fragmentation (largest possible contiguous allocation 162529280 bytes)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:125)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:249)
	at androidx.core.os.HandlerCompat.toReleases(SourceFile:26)
	at com.machiav3lli.fdroid.database.dao.ProductDao_Impl.__entityCursorConverter_comMachiav3lliFdroidDatabaseEntityProduct(SourceFile:280)
	at com.machiav3lli.fdroid.database.dao.ProductDao_Impl.queryObject(SourceFile:1)
	at com.machiav3lli.fdroid.database.dao.ProductDao_Impl.queryObject(SourceFile:4)
	at com.machiav3lli.fdroid.viewmodels.SingleListVM$products$1$1.invokeSuspend(SourceFile:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.work.Worker$2.run(SourceFile:27)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@145b063, Dispatchers.Main.immediate]```

**Comment by opk12** [comment]
Same on Samsung Android 7.1

```
FATAL EXCEPTION: main
Process: com.machiav3lli.fdroid, PID: 14979
java.lang.OutOfMemoryError: Failed to allocate a 41340 byte allocation with 4893648 free bytes and 4MB until OOM; failed due to fragmentation (required continguous free 45056 bytes where largest contiguous free 4096 bytes)
	at java.util.Arrays.copyOf(Arrays.java:3231)
	at java.util.Arrays.copyOf(Arrays.java:3204)
	at androidx.collection.SimpleArrayMap.put(r8-map-id-...:69)
	at com.machiav3lli.fdroid.data.database.dao.ProductDao_Impl$$ExternalSyntheticLambda5.invoke(r8-map-id-...:217)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performSuspending$lambda$1$$inlined$internalPerform$1$1.invokeSuspend(r8-map-id-...:47)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performSuspending$lambda$1$$inlined$internalPerform$1$1.invoke(r8-map-id-...:31)
	at androidx.room.coroutines.PassthroughConnection.transaction(r8-map-id-...:112)
	at androidx.compose.material3.TooltipStateImpl$show$2.invokeSuspend(r8-map-id-...:90)
	at androidx.compose.material3.TooltipStateImpl$show$2.invoke(r8-map-id-...:29)
	at coil3.decode.ImageSourceKt.compatTransactionCoroutineExecute(r8-map-id-...:36)
	at androidx.room.RoomDatabase$createConnectionManager$2.invoke(r8-map-id-...:60)
	at androidx.room.coroutines.PassthroughConnection.withTransaction(r8-map-id-...:9)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performSuspending$lambda$1$$inlined$internalPerform$1.invokeSuspend(r8-map-id-...:376)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performSuspending$lambda$1$$inlined$internalPerform$1.invoke(r8-map-id-...:31)
	at coil3.network.NetworkFetcher$fetch$2.invokeSuspend(r8-map-id-...:2276)
	at coil3.network.NetworkFetcher$fetch$2.invoke(r8-map-id-...:445)
	at ...
```
