### ISSUE TITLE
[Bug] app closes immediately upon opening it

### ISSUE THREAD

**Issue by nordicw0lf** [NeoApplications/Neo-Store#677]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/NeoApplications/Neo-Store/issues) and [closed](https://github.com/NeoApplications/Neo-Store/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I'm on the latest version.
- [X] I'm not using a test build (alpha/beta/release-candidate).
- [X] This issue contains only one bug.

### Describe the bug

When I open the app it instatnly closes itself, I tried to re-install it (not deleting and installing again, just downloaded the APK and re-install) it didn't work, I dont want to delete and re-install because I cant backup my favorites list

### Expected Behavior

Using the app, but it's not possible because the app closes itself

### Neo Store's Version

1.0.5

### Installation Source

Official F-Droid repo

### Last Known Working Version

1.0.5

### Relevant information

- Device: Google Pixel 7 Pro
- Android Version: 15
- ROM: (AOSP, CalyxOS, MIUI, GOS...) GrapheneOS
- Disabled battery optimization for Neo Store? Yes
- What is your selected installer? Official Fdroid repo

**Comment by nordicw0lf** [comment]
I managed to get an error log from the app:

type: crash
osVersion: google/cheetah/cheetah:15/AP3A.241005.015/2024103100:user/release-keys
flags: dev options enabled
package: com.machiav3lli.fdroid:1017, targetSdk 34
process: com.machiav3lli.fdroid
processUptime: 1821 + 298 ms
installer: com.android.packageinstaller

java.lang.IllegalArgumentException: Key "1-proton.android.pass.fdroid_406ff1e80efd189a86d10cfdf5547ee17af154b72bbff16981ec185959e9152d.apk" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SourceFile:162)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(SourceFile:34)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure(SourceFile:21)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(SourceFile:750)
	at androidx.compose.material3.ButtonKt$Button$3$1.invoke(SourceFile:1064)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SourceFile:78)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(SourceFile:38)
	at androidx.compose.foundation.AndroidOverscroll_androidKt$StretchOverscrollNonClippingLayer$1.invoke(SourceFile:14)
	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:8)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.AndroidOverscroll_androidKt$StretchOverscrollNonClippingLayer$1.invoke(SourceFile:48)
	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(SourceFile:8)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(SourceFile:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(SourceFile:97)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(SourceFile:11)
	at okhttp3.Response$Builder$initExchange$1.invoke(SourceFile:1152)
	at androidx.compose.runtime.snapshots.SnapshotIdSetKt.observe(SourceFile:60)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SourceFile:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SourceFile:153)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(SourceFile:129)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(SourceFile:55)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(SourceFile:124)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(SourceFile:87)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(SourceFile:36)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:15)
	at android.view.View.draw(View.java:24845)
	at android.view.View.updateDisplayListIfDirty(View.java:23692)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4521)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4494)
	at android.view.View.updateDisplayListIfDirty(View.java:23646)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:694)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:700)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5659)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5312)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4303)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

**Comment by machiav3lli** [comment]
Duplicate to #640 and #627 . Already fixed in current 1.0.6 alpha builds.

P.S. you can save/export then import your favorites under: settings→other→export extras

**Comment by nordicw0lf** [comment]
> Duplicate to #640 and #627 . Already fixed in current 1.0.6 alpha builds.
> 
> P.S. you can save/export then import your favorites under: settings→other→export extras

I managed to access the settings in the app before it crashed and create a backup, but its weird that it happened at all, it was fine up until 2 days ago.
